#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: PR Integration TestsDispatch Workflow

on:
  schedule:
    - cron: 0 5 * * 5

env:
  TF_VERSION: 1.12.1
  TF_LINT_VERSION: latest

jobs:
  dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        scenario:
          - standalone-scenarios-azuread.json
          - standalone-scenarios.json
          - standalone-compute.json
          - standalone-networking.json
          - standalone-dataplat.json

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: int-${{ matrix.scenario }}
          client-payload: '{"scenario": "${{ (matrix.scenario) }}", "sha": "${{ github.event.pull_request.head.sha }}"}'
